Repository warengonzaga/magic-commit, pull requests merged in 2024-10, with the labels that each got.

#8 🚀 UPDATE: v0.1.4
  .npmrc
  README.md
  contributing.md
  package.json
  source/utils/api.js
  source/utils/commit.js
  source/utils/config.json
  source/utils/openai.js
  yarn.lock
Labels: chore, hacktoberfest-accepted, maintainers only, tweak

#12 📦 new: add yes/no as select input
  .gitignore
  package.json
  source/cli.js
  source/utils/commit.js
  yarn.lock
Labels: feature, hacktoberfest-accepted, tweak

#14 📦 new: add context to git commit message
  package-lock.json
  package.json
  source/utils/config.json
  source/utils/openai.js
  yarn.lock
Labels: feature, hacktoberfest-accepted, tweak

#13 🚀 UPDATE: v0.2.5
  .gitignore
  package.json
  source/cli.js
  source/utils/commit.js
  source/utils/config.json
  source/utils/openai.js
  yarn.lock
Labels: chore, feature, hacktoberfest-accepted, maintainers only, release, tweak

#15 🚀 UPDATE: v0.2.6
  package.json
  yarn.lock
Labels: chore, fix, hacktoberfest-accepted, maintainers only, release, tweak

#24 ✨ tweak: add logo when calling flags
  source/cli.js
  yarn.lock
Labels: hacktoberfest-accepted, tweak
